:concurrency: 5
:pidfile: ./tmp/sidekiq.pid
:logfile: ./log/sidekiq.log
:verbose: true

:queues:
  - default
  - [jianggaowang, 2]

development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
